name: Pull Request checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests:

    runs-on: macos-11

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run SwiftLint
      run: swiftlint
    - name: Run tests
      run: swift test -v
